# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('service', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='accounts',
            field=models.ManyToManyField(to='notebook.Account'),
        ),
    ]
